[package]
name = "chameleon"
version = "0.1.0"
edition = "2024"

[dependencies]
toml = { version = "*" }
serde = { version = "*", features = ["derive"] }
clap = { version = "*", features = ["derive"] }
